-- +goose Up
-- Baseline: production schema in PostgreSQL dialect.
-- Created from the SQLite legacy migrations (00001..00004 merged here for the
-- postgres runtime) plus the multi-platform discriminator. The chats table
-- already carries the (platform, tg_chat_id) uniqueness so VK peer ids cannot
-- collide with Telegram chat ids in the shared database.

CREATE TABLE IF NOT EXISTS chats(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tg_chat_id BIGINT NOT NULL,
	platform TEXT NOT NULL DEFAULT 'telegram',
	username TEXT,
	state TEXT DEFAULT 'default',
	department TEXT,
	"group" TEXT,
	daily_sending_time TEXT,
	pair_sending BOOLEAN NOT NULL DEFAULT FALSE,
	update_notification BOOLEAN NOT NULL DEFAULT FALSE,
	dark_mode BOOLEAN NOT NULL DEFAULT FALSE,
	access INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT uq_chats_platform_peer UNIQUE (platform, tg_chat_id)
);
CREATE INDEX IF NOT EXISTS idx_chats_tg_chat_id ON chats(tg_chat_id);
CREATE INDEX IF NOT EXISTS idx_chats_group ON chats("group");
CREATE INDEX IF NOT EXISTS idx_chats_daily_sending_time ON chats(daily_sending_time);
CREATE INDEX IF NOT EXISTS idx_chats_created_at ON chats(created_at);
CREATE INDEX IF NOT EXISTS idx_chats_platform ON chats(platform);
CREATE INDEX IF NOT EXISTS idx_chats_platform_group ON chats(platform, "group");
CREATE INDEX IF NOT EXISTS idx_chats_platform_daily_sending_time ON chats(platform, daily_sending_time);
CREATE INDEX IF NOT EXISTS idx_chats_platform_created_at ON chats(platform, created_at);

CREATE TABLE IF NOT EXISTS schedules (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cache_key TEXT NOT NULL UNIQUE,
	data TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS update_logs(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chat_id BIGINT NOT NULL,
	kind TEXT NOT NULL,
	message_id INTEGER NOT NULL,
	data TEXT NOT NULL,
	elapsed INTEGER NOT NULL, -- milliseconds
	error TEXT,
	group_or_teacher TEXT NOT NULL DEFAULT '',
	cached BOOLEAN NOT NULL DEFAULT FALSE, -- True if schedule sent from cache
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_update_logs_chat_id ON update_logs (chat_id);
CREATE INDEX IF NOT EXISTS idx_update_logs_kind ON update_logs (kind);
CREATE INDEX IF NOT EXISTS idx_update_logs_created_at ON update_logs (created_at);

CREATE TABLE IF NOT EXISTS broadcast_task_logs(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	kind TEXT NOT NULL,
	elapsed INTEGER NOT NULL, -- milliseconds
	groups INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_broadcast_task_logs_kind ON broadcast_task_logs (kind);
CREATE INDEX IF NOT EXISTS idx_broadcast_task_logs_created_at ON broadcast_task_logs (created_at);

CREATE TABLE IF NOT EXISTS broadcast_logs(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	broadcast_task_log_id BIGINT NOT NULL REFERENCES broadcast_task_logs(id),
	chat_id BIGINT NOT NULL,
	"group" TEXT NOT NULL DEFAULT '',
	error TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_broadcast_logs_chat_id ON broadcast_logs (chat_id);
CREATE INDEX IF NOT EXISTS idx_broadcast_logs_created_at ON broadcast_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_broadcast_logs_broadcast_task_log_id ON broadcast_logs (broadcast_task_log_id);

CREATE TABLE IF NOT EXISTS recent_teachers(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chat_id BIGINT NOT NULL REFERENCES chats(id) ON DELETE CASCADE ON UPDATE CASCADE,
	teacher_id TEXT NOT NULL,
	teacher_name TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_recent_teachers_chat_id ON recent_teachers(chat_id);
CREATE INDEX IF NOT EXISTS idx_recent_teachers_created_at ON recent_teachers(created_at);