-- +goose Up
-- Manual mass-broadcast jobs dispatched from the admin bot (cmd/adminbot) to
-- per-platform workers (telegram/vk bot processes). One row is created per
-- platform for every admin command, so each worker only claims its own rows.

CREATE TABLE IF NOT EXISTS broadcast_jobs(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	audience TEXT NOT NULL, -- all | private | groups | active | by_group | by_department
	platform TEXT NOT NULL, -- telegram | vk
	spec TEXT, -- audience parameters (group name, department name, active period) as JSON
	html TEXT NOT NULL, -- message body (HTML)
	status TEXT NOT NULL DEFAULT 'pending', -- pending | sending | done | failed
	created_by BIGINT NOT NULL, -- admin chat id
	claimed_by TEXT, -- process instance (host:pid) that claimed the job
	error TEXT,
	finished_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_broadcast_jobs_platform_status ON broadcast_jobs (platform, status, created_at);

-- +goose Down
DROP TABLE IF EXISTS broadcast_jobs;