-- +goose Up
CREATE TABLE schedule_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    group_name TEXT NOT NULL,
    department_name TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (chat_id, group_name)
);

-- Переносим выбранные группы, сохраняя время и состояние рассылки в chats.
INSERT INTO schedule_subscriptions (chat_id, group_name, department_name)
SELECT id, "group", COALESCE(department, '') FROM chats
WHERE "group" IS NOT NULL AND "group" != '';

-- +goose Down
DROP TABLE schedule_subscriptions;
